### ISSUE TITLE
ThreadpoolSearchRejected and ThreadpoolWriteRejected alarms not as per the recommendation

### ISSUE THREAD

**Issue by Utkarsh-Aga** [ev2900/OpenSearch_CloudWatch_Alarms#5]
Hello,

From the Readme, it is observed that the following CW alarm configured are as follows -

| Metric name                    | Statistic | Period (second) | ComparisonOperator            | Threshold | EvaluationPeriods |
|--------------------------------|-----------|-----------------| ------------------------------|-----------|-------------------|
| ThreadpoolWriteRejected        | Maximum   | 60              | GreaterThanOrEqualToThreshold | 1         | 1                 |
| ThreadpoolSearchRejected       | Maximum   | 60              | GreaterThanOrEqualToThreshold | 1         | 1                 |

Whereas, as per the [documentation](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/cloudwatch-alarms.html), the recommendation is to set when there is a increase in the SUM, since these are cumulative metrics.

**Comment by Utkarsh-Aga** [comment]
Can the following configuration be used ? -
```
ThreadpoolSearchRejected:
      Type: AWS::CloudWatch::Alarm
      Properties:
          Metrics:
          - Expression: "DIFF(m1)"
              Id: "e1"
              Label: "Difference in ThreadpoolSearchRejected"
              ReturnData: true
          - Id: "m1"
              Label: "ThreadpoolSearchRejected"
              MetricStat: 
              Metric: 
                  Dimensions:
                      - Name: ClientId
                        Value: !Ref AWS::AccountId
                      - Name: DomainName
                        Value: Ref: OpenSearchClusterName
                  MetricName: 'ThreadpoolSearchRejected'
                  Namespace: 'AWS/ES'
              Period: 60
              Stat: SUM
              Unit: Count 
              ReturnData: false
          EvaluationPeriods: 1
          Threshold: 1
          ComparisonOperator: GreaterThanThreshold
          OKActions:
          - !Ref SNSTopic
          AlarmActions:
          - !Ref SNSTopic
```
